version: '3.7'
name: filament
networks:
    filament_net:
        driver: bridge
services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        image: server
        container_name: fl_server
        ports:
            - ${SERVER_PORT}:80
            - 5173:5173
        volumes:
            - ../:/var/www/html
        networks:
            - filament_net
        depends_on:
            - mysql
    mysql:
        container_name: fl_mysql
        image: mysql:8
        command: --max_allowed_packet=92505856
        networks:
            - filament_net
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./data/mysql:/var/lib/mysql
